sudo: required
dist: xenial
language: php
php:
- 7.1
env:
- NODE_RELEASE=10.x
install:
- composer self-update -q
- composer install
- if [ ! -f .env ]; then cp .env.example .env; fi
- sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}"|
  sudo -E bash -
- sudo apt-get install -y nodejs
- npm install
script:
- "./vendor/bin/phpunit"
- php artisan js-localization:export
- npm run production
cache:
  directories:
  - vendor
  - node_modules
before_deploy:
- git config --local user.name "${GH_USER_NAME}"
- git config --local user.email "${GH_USER_EMAIL}"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- zip -r "debrief-$TRAVIS_TAG.zip" . -x"*node_modules*" -x"*.git*"
deploy:
  skip_cleanup: true
  draft: true
  file_glob: true
  provider: releases
  api_key:
    secure: Hku7GhDFAtPol/oNNK9yXRQLsyMuVTl+3BIVqn7ZkYJ7Krok92i9E8WoJRR2eZzHvZVHQWUV8v1t5jFEGSvkEPkb8Wu/bx/40BCUCMx3ODYjp64By6K5Rl+7A4LpvDa57JiB3p1IlnJP81Lj8x+EeXHUIP2a+sLcqwluTOlYJWBqW07N56DsA1HSJl13VceCTF4Y/J0T0a3KkDqWkh74qFACVM4edFxWuMo/2RBySe08tulj9HCc+YP6XRAChyCcOisTQSSCCkRwxLzLPykm67osRG9ZEw5wa4tAwnXl++AyLXOiEcKPu7LC18ijIhaKiYwBRJnzvrGr+9QJ5mS8m88WNHuE8dx/MFphGwKwqSET/BHHgezpYJ+TpgrieSE7PsBRHd97X3MjZraA9pG05qbozMArRRbav03ktN20qtafHtV28ZChww1JDhH8Fv8RMQA1PwMIrlXCzBDxkmSVNpjYlrrbOyKZljOWn0pm3BSNq/as8Zo8DUiA1AkEB99kqne0ALm5DC8rEg1BcUWtEEenzV95WbKoEokn7Bb6DzCMKnKIjnyrdZ2A7CvdjIHwZ6qmCr7cRwIRvp3FBZFRPCcAbecpxXPOGueG9cJxrW8Da4tG7AsTNfqqKkvSrWthnOBtTdkBCYLYx8FgMs02uNxYS+fJJ0l/DaGLM8Frwvs=
  file: debrief-$TRAVIS_TAG.zip
  on:
    repo: dandelionmood/debrief
    branch: feature/travis