language: generic
jobs:
  include:
    - stage: "Tests"                # naming the Tests stage
      name: "Unit Tests"            # names the first Tests stage job
      script: ./vendor/bin/phpunit
cache:
  directories:
  - vendor
  - node_modules