language: generic
before_install:
  - composer install
  - npm install
php:
  - '7.0'
node_js:
  - '10'
jobs:
  include:
    - stage: "Tests"
      name: "Unit Tests"
      script: ./vendor/bin/phpunit
    - stage: "Build"
      name: "JS/CSS compilation"
      script: npm run production
cache:
  directories:
  - vendor
  - node_modules