sudo: required
dist: xenial
language: php
php:
- 7.1
env:
- NODE_RELEASE=10.x
install:
- composer self-update -q
- composer install
- if [ ! -f .env ]; then cp .env.example .env; fi
- sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
- sudo apt-get install -y nodejs
- npm install
script:
- "./vendor/bin/phpunit"
- php artisan js-localization:export
- npm run production
cache:
  directories:
  - vendor
  - node_modules
before_deploy:
# Set up git user name and tag this commit
- git config --local user.name "${GH_USER_NAME}"
- git config --local user.email "${GH_USER_EMAIL}"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- zip -r "debrief-$TRAVIS_TAG.zip" . -x"*node_modules*" -x"*.git*"
deploy:
  provider: releases
  skip_cleanup: true
  draft: true
  api_key:
    secure: "K9Wl2Qog6uMi+6yfLHs2xdcvrzHHPSwX4WNHnNYaN6PXRfHfg9c5LTmPBW9rEz6voA55wOG4fTmIVSvpE6R50uJ86ettdZu+KJqIEp8jl/cmJIYZyKVaTEWXiE8qaiW/oCAwlQhIVLgucYcAnx+Oo8iW/M5KZloCkv47CF5G/rbGo2hxbTa5vsrS13/f7pTgoCItQ5RmL4pLW+TToVyFb/9QHSDN5YFiQRu9Avs8wCNm2jiml2tHoU0p/EtaWU7vJ5g7viuZtIqj463WktCAbLK+vCPt9EekDyz4VHfb0igRNdEeepoKBSF6RcR9+nWY1xy3/gEiRJNr/O1j7tJ9Iow5RQ3AorXpQO9OGef3+sk9buFi5DDR+E+MSrDAsDoAvqXIR6fNZzehugI0y/kuWeyOsz8Qbn5qFlWrwc0k+ObOq3YCzEhAj/oQlNYM6UtSyD0n5G99G4zWsYcSGLBLbIQf5h0HBupfoAvAy445q04iTUrc1u60IPRP04NdnXtP1JtUggnVGrbl82rVV2GgmMaBjTdbN02YvcP2pWqxoqKwP7XDN6jHERrm1VmID2z1/SvCqvDWhXfZL04tnOQJ85xmHUkWaJ64RishYPkEAvcmFBE/us/0oNeihmIIUmfbyx58nEiMVUc903+g944CKgV4g9lZ5P6S2+yFuS09zAs="
  file_glob: true
  file: 
  - "debrief-$TRAVIS_TAG.zip"
  on:
    branch: feature/travis
    repo: dandelionmood/debrief
